package com.soside.backend.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "marriage_record")
public class MarriageRecord {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "partner1_id")
    private Person partner1;

    @ManyToOne
    @JoinColumn(name = "partner2_id")
    private Person partner2;

    private String marriagePlace;
    private String marriageDate;
    private String officiantName;
    private String witness1Name;
    private String witness2Name;
    private String marriageType;
    private String contractType;
    private String previousMarriages;

    // Getters and Setters are generated by Lombok
}
