package com.soside.backend.enums;

public enum HealthRecordType {
    VACCINATION, BLOOD_TYPE, ILLNESS, ALLERGY, SURGERY, HOSPITALIZATION,
    CONSULTATION, EXAMINATION, TREATMENT, MEDICATION, OTHER
}
